package tsFile

import (
	"fmt"
	"gitlab.com/loxe-tools/go-base-library/brand"
)

// SourceCode will build the file source code, including the file imports
// source code
//
// Note that you need to pass the name of the library that
// generated it, in order to provide good debug information
// inside the generated file
func (f *TsFile) SourceCode(libraryThatGeneratedIt string) ([]byte, error) {
	headerBrand := fmt.Sprintf("/*%s*/",
		brand.WithSubtitle(brand.GeneratedFileMessage+libraryThatGeneratedIt))

	sourceCode := headerBrand + "\n" +
		f.privateImports.SourceCode() +
		f.sourceCode + "\n" +
		fmt.Sprintf("// Code generated by %s, DO NOT EDIT.", libraryThatGeneratedIt) + "\n"

	return []byte(sourceCode), nil
}
